---
deployment:
  tasks:
    - /bin/bash -c "source /home/putdfhal/nodevenv/gulf-estates/gulf-frontend/24/bin/activate && cd /home/putdfhal/gulf-estates/gulf-frontend && git pull origin main && pnpm install --frozen-lockfile && pnpm run build && mkdir -p tmp && touch tmp/restart.txt"
